{  
    "Envelope":{  
      "Body":{  
        "enviaDadosWSCliente":{  
          "catracaParams":{  
            "cdBarras":{  
              "_xmlns":"",
              "__text":"string"
            },
            "nrIdentidade":{  
              "_xmlns":"",
              "__text":"string"
            },
            "nrSeqTipo":{  
              "_xmlns":"",
              "__text":"string"
            },
            "xml":{  
              "_xmlns":"",
              "__text":"string"
            },
            "ieTipoDocumento":{  
              "_xmlns":"",
              "__text":"string"
            },
            "nrDocumento":{  
              "_xmlns":"",
              "__text":"string"
            },
            "dtEntrada":{  
              "_xmlns":"",
              "__text":"string"
            },
            "hrEntrada":{  
              "_xmlns":"",
              "__text":"string"
            },
            "dsCracha":{  
              "_xmlns":"",
              "__text":"string"
            },
            "nmVisitante":{  
              "_xmlns":"",
              "__text":"string"
            },
            "codigosControleAcessoVisita":{  
              "_xmlns":"",
              "__text":"string"
            }
          },
          "_xmlns":"http://AcessoCatraca.webServiceServers.wsi.wheb.com.br/"
        },
        "__prefix":"soap"
      },
      "_xmlns:xsi":"http://www.w3.org/2001/XMLSchema-instance",
      "_xmlns:xsd":"http://www.w3.org/2001/XMLSchema",
      "_xmlns:soap":"http://schemas.xmlsoap.org/soap/envelope/",
      "__prefix":"soap"
    }
  }